/* ================================================================
   DRAGON GAMING PLATFORMS — CDN / STANDALONE DATA CATALOG
   ================================================================ */
const CDN_BASE = "https://dragon-gaming-platforms.github.io/Dragon-Gaming-Platforms/";

const GAMES_DATA = [
  {
    id: "eaglercraft-1-12-2-wasm",
    name: "Eaglercraft 1.12.2 WASM",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-1.12.2-offline-WASM.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Sandbox", "Survival", "3D", "WASM"],
    badge: "WASM",
    desc: "Full Minecraft 1.12.2 running offline directly in your browser via WebAssembly.",
    controls: "WASD: Move | Space: Jump | Left Click: Mine / Attack | Right Click: Place / Interact | E: Inventory | Esc: Pause"
  },
  {
    id: "eaglercraft-1-12-2-js",
    name: "Eaglercraft 1.12.2 JS",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-JS-1.12.2.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Sandbox", "Survival", "3D"],
    badge: "3D",
    desc: "JavaScript client for Minecraft 1.12.2 with online multiplayer and singleplayer worlds.",
    controls: "WASD: Move | Space: Jump | Mouse: Look / Mine | E: Inventory | Esc: Pause"
  },
  {
    id: "eaglercraft-1-8-8-js",
    name: "Eaglercraft 1.8.8 JS",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-JS-1.8.8.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Sandbox", "Survival", "3D", "Multiplayer"],
    badge: "Popular",
    desc: "Classic Minecraft 1.8.8 with server browser, custom skins, and fluid combat.",
    controls: "WASD: Move | Space: Jump | Mouse: Look / Mine | E: Inventory | T: Chat"
  },
  {
    id: "eaglercraft-1-8-8-wasm",
    name: "Eaglercraft 1.8.8 WASM",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-1.8.8-offline-WASM.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Sandbox", "Survival", "3D", "WASM"],
    badge: "WASM",
    desc: "Ultra-fast WebAssembly offline edition of Minecraft 1.8.8.",
    controls: "WASD: Move | Space: Jump | Left/Right Click: Mine/Place | E: Inventory"
  },
  {
    id: "balatro",
    name: "Balatro",
    path: CDN_BASE + "games/singlefiles/Balatro.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Cards", "Roguelike", "Strategy"],
    badge: "Featured",
    desc: "Poker roguelike deck builder \u2014 trigger synergistic jokers and execute wild combos.",
    controls: "Mouse / Touch: Select cards, buy jokers, open booster packs"
  },
  {
    id: "bloons-td4",
    name: "Bloons TD 4",
    path: CDN_BASE + "games/singlefiles/Bloons-TD4.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Tower Defense", "Classic"],
    badge: "Featured",
    desc: "The iconic balloon-popping defense game \u2014 deploy dart monkeys, tack shooters, and mortar cannons.",
    controls: "Mouse: Select and place monkey defense towers on track"
  },
  {
    id: "drive-mad",
    name: "Drive Mad",
    path: CDN_BASE + "games/singlefiles/Drive-Mad.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Driving", "Physics", "Action", "3D"],
    badge: "Popular",
    desc: "High-tension 3D physics truck driving with crazy stunts, balance traps, and obstacle courses.",
    controls: "W / Up Arrow: Accelerate | S / Down Arrow: Reverse & Brake | A / D: Balance truck"
  },
  {
    id: "escape-road",
    name: "Escape Road",
    path: CDN_BASE + "games/singlefiles/Escape-Road.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Driving", "Action", "3D", "Endless"],
    badge: "3D Action",
    desc: "Fast-paced high-speed getaway driving game \u2014 weave through traffic and evade police chases.",
    controls: "A / D or Left / Right: Steer vehicle | Space: Drift / Handbrake"
  },
  {
    id: "hole-io",
    name: "Hole.io",
    path: CDN_BASE + "games/singlefiles/Hole.io.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Multiplayer", "Physics", "3D"],
    badge: "Popular",
    desc: "Control a growing black hole, swallow city buildings, cars, and opponents in an arena showdown.",
    controls: "Mouse Drag / Arrow Keys / WASD: Move hole around city"
  },
  {
    id: "moto-x3m-2",
    name: "Moto X3M 2",
    path: CDN_BASE + "games/singlefiles/Moto-x3m-2.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Driving", "Physics", "Action"],
    badge: "Popular",
    desc: "Adrenaline-packed motocross stunt racer with lethal traps, explosive loops, and timed trials.",
    controls: "Up / W: Accelerate | Down / S: Brake | Left / Right or A / D: Tilt & Front/Backflips"
  },
  {
    id: "ragdoll-archers",
    name: "Ragdoll Archers",
    path: CDN_BASE + "games/singlefiles/Ragdoll-Archers.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Physics", "Shooter"],
    badge: "Physics",
    desc: "Physics-driven ragdoll archery battle \u2014 aim arrows, unlock special arrowheads, and defeat enemy waves.",
    controls: "Mouse Drag & Release: Aim bow and fire arrow"
  },
  {
    id: "recoil",
    name: "Recoil",
    path: CDN_BASE + "games/singlefiles/Recoil.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Physics", "Shooter"],
    badge: "Action",
    desc: "Clever puzzle shooter where your only way to move is using weapon recoil forces.",
    controls: "Mouse: Aim | Click: Shoot weapon and propel yourself with recoil"
  },
  {
    id: "snowrider-3d",
    name: "Snow Rider 3D",
    path: CDN_BASE + "games/singlefiles/Snowrider.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Sports", "3D", "Endless"],
    badge: "3D",
    desc: "Ride your snow sled down treacherous mountain peaks, dodge giant pine trees, rocks, and jump chasms.",
    controls: "Left / Right Arrows or A / D: Steer sled | Up Arrow or Space: Jump"
  },
  {
    id: "vex-8",
    name: "Vex 8",
    path: CDN_BASE + "games/singlefiles/Vex-8.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Action", "Platformer", "Parkour"],
    badge: "Action",
    desc: "Extreme precision stickman parkour with buzzsaws, trampolines, grappling hooks, and laser grids.",
    controls: "WASD / Arrow Keys: Run, jump, slide, wall-climb"
  },
  {
    id: "awesome-tanks-2",
    name: "Awesome Tanks 2",
    path: CDN_BASE + "games/singlefiles/awesometanks2.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Shooter", "Tanks"],
    badge: "Action",
    desc: "Top-down arcade tank warfare \u2014 obliterate enemy spawners, collect gold coins, and upgrade turrets.",
    controls: "WASD / Arrow Keys: Drive tank | Mouse: Aim and fire cannons"
  },
  {
    id: "dreadhead-parkour",
    name: "Dreadhead Parkour",
    path: CDN_BASE + "games/singlefiles/dreadheadparkour.htm",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Action", "Platformer", "Parkour"],
    badge: "Parkour",
    desc: "Stylized high-speed parkour runner \u2014 slide under spikes, vault rooftop gaps, and collect gold rings.",
    controls: "WASD / Arrow Keys: Move, jump, slide, flip"
  },
  {
    id: "borg-games",
    name: "Borg Games Hub",
    path: CDN_BASE + "games/singlefiles/Borg-Games.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Retro", "Arcade", "Compilation"],
    badge: "Hub",
    desc: "Classic unblocked web games arcade hub featuring multiple vintage mini-games.",
    controls: "Mouse & Keyboard: Navigate catalog and play games"
  },
  {
    id: "q1k3",
    name: "Q1K3 (Quake 13K)",
    path: CDN_BASE + "games/q1k3/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "3D", "FPS", "Retro"],
    badge: "3D FPS",
    desc: "Legendary homage to 1996 Quake written in pure WebGL with dynamic lighting, monsters, and guns.",
    controls: "WASD: Move | Mouse: Look & Shoot | Space: Jump | 1-2: Switch Weapons"
  },
  {
    id: "space-huggers",
    name: "Space Huggers",
    path: CDN_BASE + "games/space-huggers/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Platformer", "Shooter", "Roguelike"],
    badge: "Roguelike",
    desc: "Procedural roguelike run-and-gun action shooter with destructible environments and LittleJS engine.",
    controls: "WASD / Arrows: Move & Jump | Mouse / Z: Aim & Shoot | R: Reload"
  },
  {
    id: "radius-raid",
    name: "Radius Raid",
    path: CDN_BASE + "games/radius-raid/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Arcade", "Shooter", "Vector"],
    badge: "Arcade",
    desc: "Frenzied vector arena space shooter with particle glow effects, enemy swarms, and powerups.",
    controls: "WASD / Arrows: Move | Mouse: Aim & Fire | Space: Bomb"
  },
  {
    id: "bounce-back",
    name: "BounceBack",
    path: CDN_BASE + "games/bounce-back/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Adventure", "Retro"],
    badge: "Action",
    desc: "Top-down procedural Zelda-like adventure where your trusty boomerang is your only weapon.",
    controls: "WASD / Arrows: Move | Mouse / Space: Throw Boomerang | E: Interact"
  },
  {
    id: "doom-13k",
    name: "Doom 13K",
    path: CDN_BASE + "games/doom-13k/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "3D", "FPS", "Retro"],
    badge: "3D FPS",
    desc: "Micro 3D raycaster shooter capturing the raw essence of retro DOOM inside 13 kilobytes.",
    controls: "WASD / Arrows: Move & Turn | Space / Ctrl: Fire Weapon | E: Open Doors"
  },
  {
    id: "dante-13k",
    name: "Dante (13K)",
    path: CDN_BASE + "games/dante-13k/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "3D", "Hack & Slash"],
    badge: "3D Action",
    desc: "Isometric 3D hack-and-slash brawler journeying through the 9 circles of hell with combo combat.",
    controls: "WASD / Arrows: Move | J / Space: Attack | K: Dash | L: Special"
  },
  {
    id: "diablo-js",
    name: "Diablo JS",
    path: CDN_BASE + "games/diablo-js/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["RPG", "Action", "Isometric", "Retro"],
    badge: "RPG",
    desc: "Isometric HTML5 canvas action RPG engine with procedural dungeons, loot drops, and skeleton hordes.",
    controls: "Mouse: Click to move, attack enemies, and pick up items"
  },
  {
    id: "emberwind",
    name: "Emberwind",
    path: CDN_BASE + "games/emberwind/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Platformer", "Action", "Adventure"],
    badge: "Platformer",
    desc: "High-production fairytale action platformer \u2014 soar with your magical cane and fight gremlins.",
    controls: "Arrow Keys: Move & Crouch | Space / Z: Cane Attack | X: Jump"
  },
  {
    id: "executive-man",
    name: "Executive Man",
    path: CDN_BASE + "games/executive-man/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Action", "Platformer", "Retro"],
    badge: "Retro",
    desc: "Mega Man style retro action platformer climbing the corporate ladder with briefcase blasters.",
    controls: "Arrow Keys / WASD: Move & Jump | Space / Z: Shoot | X: Slide"
  },
  {
    id: "pixel-platformer",
    name: "Pixel Platformer",
    path: CDN_BASE + "games/pixel-platformer/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Platformer", "Action", "Pixel"],
    badge: "Platformer",
    desc: "Crisp EntityJS pixel platformer with responsive wall-jumping, collectibles, and hazards.",
    controls: "Left / Right: Run | Space / Up: Jump | Down: Duck / Fall"
  },
  {
    id: "space-shooter",
    name: "Space Shooter",
    path: CDN_BASE + "games/space-shooter/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Shooter", "Space"],
    badge: "Space",
    desc: "Smooth arcade space shooter with laser upgrades, shield generators, and mothership bosses.",
    controls: "WASD / Arrow Keys: Steer ship | Space / Mouse Click: Fire cannons"
  },
  {
    id: "canyon-runner",
    name: "Canyon Runner",
    path: CDN_BASE + "games/canyon-runner/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["3D", "Driving", "Action"],
    badge: "3D Runner",
    desc: "High-speed 3D flight simulator navigating narrow desert canyons without crashing.",
    controls: "Arrow Keys / WASD: Steer & Pitch Jet | Space: Afterburner Boost"
  },
  {
    id: "circus-charlie",
    name: "Circus Charlie",
    path: CDN_BASE + "games/circus-charlie/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Classic"],
    badge: "Retro Arcade",
    desc: "Faithful recreation of Konami classic circus performer jumping through fiery hoops on a lion.",
    controls: "Left / Right: Walk / Run | Space / Up: Jump through hoops"
  },
  {
    id: "alges-escapade",
    name: "Alges Escapade",
    path: CDN_BASE + "games/alges-escapade/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Platformer", "Adventure", "Action"],
    badge: "Adventure",
    desc: "Charming 2D puzzle platformer with physics-driven level mechanics and quirky creatures.",
    controls: "Arrow Keys / A/D: Move | Space / W: Jump | Down: Crouch"
  },
  {
    id: "ekg-runner",
    name: "EKG Runner",
    path: CDN_BASE + "games/ekg-runner/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Action", "Endless", "Rhythm"],
    badge: "Runner",
    desc: "Unique rhythm pulse runner where you surf along dynamic electrocardiogram heartbeat waves.",
    controls: "Space / Up Arrow / Click: Jump across pulse spikes"
  },
  {
    id: "loderunner",
    name: "Lode Runner",
    path: CDN_BASE + "games/loderunner/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Platformer", "Retro"],
    badge: "Classic",
    desc: "Total recall recreation of the 1983 platform puzzle legend with all 150 original levels.",
    controls: "Arrow Keys: Move & Climb Ladders | Z / X: Dig hole left / right"
  },
  {
    id: "roguish",
    name: "Roguish",
    path: CDN_BASE + "games/roguish/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["RPG", "Roguelike", "Dungeon"],
    badge: "Roguelike",
    desc: "Turn-based roguelike dungeon crawler with tactical grid positioning, potions, and spells.",
    controls: "WASD / Arrow Keys: Move & Bump Attack | 1-4: Cast Spells | I: Inventory"
  },
  {
    id: "protocol-390",
    name: "Protocol 390",
    path: CDN_BASE + "games/protocol-390/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Adventure", "Sci-Fi", "Cyberpunk"],
    badge: "Sci-Fi",
    desc: "Atmospheric cyberpunk adventure game unraveling dark corporate conspiracies.",
    controls: "WASD / Arrow Keys: Move | E / Space: Interact with terminals and NPCs"
  },
  {
    id: "puzzlescript",
    name: "PuzzleScript Gallery",
    path: CDN_BASE + "games/puzzlescript/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Retro", "Engine"],
    badge: "Puzzle",
    desc: "Interactive showcase of Stephen Lavelle innovative puzzle engine with multiple built-in games.",
    controls: "Arrow Keys / WASD: Move | Z / U: Undo step | R: Restart puzzle"
  },
  {
    id: "edge-not-found",
    name: "Edge Not Found",
    path: CDN_BASE + "games/edge-not-found/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Sokoban", "Logic"],
    badge: "Puzzle",
    desc: "Mind-bending Sokoban puzzle taking place on an infinitely wrapping 4D toroidal grid.",
    controls: "WASD / Arrow Keys: Move | Z / U: Undo | R: Restart level"
  },
  {
    id: "behind-asteroids",
    name: "Behind Asteroids",
    path: CDN_BASE + "games/behind-asteroids/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Space", "Sci-Fi"],
    badge: "JS13K",
    desc: "JS13K winner flipping Asteroids upside down \u2014 defend asteroid mining rigs from raiders.",
    controls: "WASD / Arrows: Steer ship | Space / Click: Shoot lasers | Shift: Boost"
  },
  {
    id: "island-builder",
    name: "Island Builder",
    path: CDN_BASE + "games/island-builder/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "Sandbox", "3D"],
    badge: "Sandbox",
    desc: "Relaxing 3D isometric island builder \u2014 craft Mediterranean voxel villages on sunlit shores.",
    controls: "Mouse Click / Drag: Place terrain, roads, houses, trees | Mouse Wheel: Zoom"
  },
  {
    id: "black-hole-square",
    name: "Black Hole Square",
    path: CDN_BASE + "games/black-hole-square/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Physics", "Spatial"],
    badge: "Puzzle",
    desc: "Gravitational spatial puzzle game manipulating celestial singularities and cosmic geometry.",
    controls: "Mouse: Place & rotate gravity deflector tiles | Space: Test orbit"
  },
  {
    id: "xx142-b2",
    name: "xx142-b2.exe",
    path: CDN_BASE + "games/xx142-b2/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Adventure", "Sci-Fi", "Retro"],
    badge: "Retro",
    desc: "Immersive retro sci-fi cyber terminal text adventure unraveling alien transmission logs.",
    controls: "Keyboard: Type terminal commands (help, scan, decode, access)"
  },
  {
    id: "os13k",
    name: "OS13k Game Hub",
    path: CDN_BASE + "games/os13k/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Sandbox", "Retro", "Compilation"],
    badge: "Hub",
    desc: "Compact retro operating system containing built-in arcade games, paint tools, and music synth.",
    controls: "Mouse / Keyboard: Click desktop icons and run mini apps"
  },
  {
    id: "space-cadet-pinball",
    name: "3D Pinball: Space Cadet",
    path: CDN_BASE + "games/space-cadet-pinball/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "3D", "Classic"],
    badge: "Popular",
    desc: "The nostalgic Windows XP 3D Space Cadet Pinball compiled to WebAssembly with authentic sound effects.",
    controls: "Space: Launch ball | Z / / : Left / Right flippers | Space: Bump table | F2: New Game"
  },
  {
    id: "heroine-dusk",
    name: "Heroine Dusk",
    path: CDN_BASE + "games/heroine-dusk/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["RPG", "Adventure", "Retro"],
    badge: "Retro",
    desc: "Classic turn-based 8-bit dungeon crawler RPG with spellcasting, town shops, and enemy encounters.",
    controls: "WASD / Arrow Keys: Navigate dungeon grid | Mouse: Select combat actions"
  },
  {
    id: "clumsy-bird",
    name: "Clumsy Bird",
    path: CDN_BASE + "games/clumsy-bird/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Casual", "Retro"],
    badge: "Arcade",
    desc: "MelonJS-powered open-source Flappy Bird remake with smooth 60 FPS physics and particle FX.",
    controls: "Spacebar / Up Arrow / Mouse Click: Flap wings"
  },
  {
    id: "minesweeper",
    name: "Minesweeper Classic",
    path: CDN_BASE + "games/minesweeper/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Classic", "Strategy"],
    badge: "Classic",
    desc: "Authentic Windows 95 style Minesweeper with Beginner, Intermediate, and Expert grid configurations.",
    controls: "Left Click: Reveal cell | Right Click: Place flag | Both: Chording"
  },
  {
    id: "duck-hunt",
    name: "Duck Hunt",
    path: CDN_BASE + "games/duck-hunt/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Classic"],
    badge: "Retro",
    desc: "Faithful recreation of the iconic NES light-gun shooter with flying ducks and the laughing dog.",
    controls: "Mouse: Aim crosshair | Left Click: Pull trigger"
  },
  {
    id: "sokoban",
    name: "Sokoban",
    path: CDN_BASE + "games/sokoban/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Classic", "Retro"],
    badge: "Puzzle",
    desc: "Original Japanese warehouse puzzle game \u2014 push every crate onto its designated target square.",
    controls: "WASD / Arrow Keys: Move pusher | R: Restart level | U: Undo move"
  },
  {
    id: "snake",
    name: "Snake HTML5",
    path: CDN_BASE + "games/snake/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Classic", "Retro"],
    badge: "Classic",
    desc: "Clean, responsive HTML5 canvas recreation of the legendary Nokia mobile Snake game.",
    controls: "Arrow Keys / WASD: Steer snake direction"
  },
  {
    id: "sudoku",
    name: "Sudoku Master",
    path: CDN_BASE + "games/sudoku/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Strategy", "Classic"],
    badge: "Puzzle",
    desc: "Interactive 9x9 Sudoku grid generator with difficulty tiers, error checking, and note-taking.",
    controls: "Click cell: Select | 1-9: Enter number | Del / Backspace: Erase note"
  },
  {
    id: "chess",
    name: "HTML5 Chess",
    path: CDN_BASE + "games/chess/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Board", "Classic"],
    badge: "Classic",
    desc: "Clean 2-player and AI chess board with legal move indicators, capture history, and checkmate detection.",
    controls: "Mouse Click / Drag: Pick up and move chess pieces"
  },
  {
    id: "micropolisjs",
    name: "MicropolisJS (SimCity)",
    path: CDN_BASE + "games/micropolisjs/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "Strategy", "Classic"],
    badge: "Classic Sim",
    desc: "Full JavaScript port of Will Wright original SimCity (Micropolis) engine running in browser.",
    controls: "Mouse: Select construction tools, zone residential/commercial/industrial, manage tax budget"
  },
  {
    id: "solitaire",
    name: "Klondike Solitaire",
    path: CDN_BASE + "games/solitaire/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Cards", "Classic", "Puzzle"],
    badge: "Classic",
    desc: "Standard Klondike Solitaire with draw-1 and draw-3 modes, auto-complete, and scoring.",
    controls: "Mouse Drag / Double Click: Move cards to foundation piles"
  },
  {
    id: "asteroids",
    name: "Vector Asteroids",
    path: CDN_BASE + "games/asteroids/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Shooter"],
    badge: "Retro",
    desc: "High-contrast monochrome vector physics space shooter inspired by Atari arcade 1979 masterpiece.",
    controls: "Left / Right: Rotate ship | Up Arrow: Thruster | Spacebar: Fire laser blaster"
  },
  {
    id: "skifree",
    name: "SkiFree HTML5",
    path: CDN_BASE + "games/skifree/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Sports", "Retro", "Arcade"],
    badge: "Retro",
    desc: "Downhill ski slalom simulator complete with moguls, jumps, snowboarders, and the terrifying Abominable Snow Monster.",
    controls: "Left / Right: Steer skier | Down: Accelerate | Up: Brake | Space: Jump"
  },
  {
    id: "tower-defense",
    name: "Canvas Tower Defense",
    path: CDN_BASE + "games/tower-defense/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Tower Defense", "Arcade"],
    badge: "Strategy",
    desc: "Top-down tactical defense \u2014 place laser turrets, flak cannons, and freeze towers along enemy path.",
    controls: "Mouse: Select tower type and place along the road | Space: Fast forward wave"
  },
  {
    id: "2048",
    name: "2048 Original",
    path: CDN_BASE + "games/2048/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Math", "Casual"],
    badge: "Popular",
    desc: "Gabriele Cirulli addictive sliding tile number puzzle \u2014 merge matching numbers to achieve 2048.",
    controls: "Arrow Keys / WASD / Swipe: Slide all tiles in one direction"
  },
  {
    id: "1255-burgomaster",
    name: "1255 Burgomaster",
    path: CDN_BASE + "games/1255-burgomaster/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Strategy", "Simulation", "Retro"],
    badge: "Strategy",
    desc: "Medieval city-state political management simulator \u2014 balance taxes, food supplies, and citizen approval.",
    controls: "Mouse: Adjust municipal sliders, manage trade policies, review decrees"
  },
  {
    id: "3d-city",
    name: "3D City Engine",
    path: CDN_BASE + "games/3d.city/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "3D", "Sandbox"],
    badge: "3D Sim",
    desc: "Three.js powered 3D procedural voxel metropolis generator with dynamic camera controls and weather.",
    controls: "Mouse Drag: Rotate view | Scroll: Zoom | WASD: Pan camera | Click: Inspect district"
  },
  {
    id: "ancient-beast",
    name: "Ancient Beast",
    path: CDN_BASE + "games/AncientBeast/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Turn-Based", "RPG"],
    badge: "Turn-Based",
    desc: "Turn-based tactical creature combat on a hexagonal battleground with unique elemental beasts.",
    controls: "Mouse: Select creature, choose abilities, target enemy hexes"
  },
  {
    id: "a-dark-room",
    name: "A Dark Room",
    path: CDN_BASE + "games/adarkroom/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["RPG", "Adventure", "Incremental"],
    badge: "Story",
    desc: "Critically acclaimed minimalist text-based role playing mystery game \u2014 stoke the fire and survive.",
    controls: "Mouse: Click buttons to light fire, gather wood, explore outside"
  },
  {
    id: "aquastax",
    name: "Aquastax",
    path: CDN_BASE + "games/aquastax/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Physics", "Casual"],
    badge: "Physics",
    desc: "Fluid mechanics puzzle game where you manage pipes and water currents to fill floating tanks.",
    controls: "Mouse: Click pipes to rotate direction and seal leak points"
  },
  {
    id: "arashi-js",
    name: "Arashi Tempest",
    path: CDN_BASE + "games/arashi-js/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Shooter"],
    badge: "Retro",
    desc: "Vector tube shooter homage to classic Tempest \u2014 crawl around geometric perimeters and blast geometric enemies.",
    controls: "Left / Right: Move along edge | Spacebar: Fire blaster | Enter: Superzapper"
  },
  {
    id: "asdf",
    name: "ASDF Typing Arcade",
    path: CDN_BASE + "games/asdf/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Casual", "Retro"],
    badge: "Typing",
    desc: "High-speed rhythm keyboard typing test \u2014 hit falling keys in sync with the beat.",
    controls: "Keyboard: Press falling letters (A, S, D, F) in sequence"
  },
  {
    id: "ball-and-wall",
    name: "Ball & Wall Breakout",
    path: CDN_BASE + "games/ball-and-wall/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Physics"],
    badge: "Retro",
    desc: "Polished Breakout brick-breaker arcade with power-ups, multiball, and laser paddles.",
    controls: "Mouse / Left-Right Arrows: Move paddle | Space: Launch ball"
  },
  {
    id: "banania",
    name: "Banania",
    path: CDN_BASE + "games/Banania/banania.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Classic", "Retro"],
    badge: "Retro",
    desc: "Classic DOS maze game \u2014 guide the monkey to eat all bananas while outsmarting angry monsters.",
    controls: "Arrow Keys: Move monkey | Esc: Pause"
  },
  {
    id: "blockrain",
    name: "Blockrain Tetris",
    path: CDN_BASE + "games/blockrain/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Arcade", "Puzzle", "Retro"],
    badge: "Retro",
    desc: "Retro pixel-art falling block puzzle with smooth line-clear animations and chiptune vibes.",
    controls: "Left / Right: Move block | Up: Rotate | Down: Soft drop | Space: Hard drop"
  },
  {
    id: "canvas-tetris",
    name: "Canvas Tetris",
    path: CDN_BASE + "games/canvas-tetris/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Arcade", "Puzzle", "Classic"],
    badge: "Classic",
    desc: "Lightweight, ultra-responsive HTML5 Canvas implementation of standard competitive Tetris.",
    controls: "Left / Right: Shift | Up / X: Rotate | Down: Soft drop | Space: Hard drop"
  },
  {
    id: "crappybird",
    name: "CrappyBird",
    path: CDN_BASE + "games/CrappyBird/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Casual", "Flappy"],
    badge: "Arcade",
    desc: "Humorous Flappy Bird parody \u2014 tap to flap your wings and weave through tricky pipe obstacles.",
    controls: "Spacebar / Mouse Click / Touch: Flap wings"
  },
  {
    id: "crystalquest",
    name: "CrystalQuest",
    path: CDN_BASE + "games/CrystalQuest/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Shooter", "Retro"],
    badge: "Retro",
    desc: "Classic arcade arena shooter \u2014 vacuum up all crystals while blasting invading alien swarms.",
    controls: "Mouse: Move ship | Mouse Click: Fire blaster | Space: Smart Bomb"
  },
  {
    id: "enduro",
    name: "Enduro",
    path: CDN_BASE + "games/enduro/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Racing", "Retro", "Classic"],
    badge: "Atari Retro",
    desc: "Tribute to the classic Atari 2600 endurance racer with dynamic weather, fog, and day/night cycles.",
    controls: "Up Arrow: Accelerate | Down Arrow: Brake | Left / Right Arrows: Steer"
  },
  {
    id: "hexgl",
    name: "HexGL",
    path: CDN_BASE + "games/HexGL/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Racing", "3D", "Sci-Fi"],
    badge: "3D",
    desc: "Futuristic high-speed anti-gravity 3D racer built in WebGL with stunning Three.js graphics.",
    controls: "Up / W: Accelerate | A / D or Left / Right: Steer | Q / E: Air brakes | Space: Boost"
  },
  {
    id: "hextris",
    name: "Hextris",
    path: CDN_BASE + "games/Hextris/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Arcade", "Hexagonal"],
    badge: "Popular",
    desc: "Fast-paced hexagonal puzzle \u2014 rotate the center hexagon to match 3 or more blocks of the same color.",
    controls: "Left / Right Arrows or A / D: Rotate hexagon | Down Arrow: Speed up block fall"
  },
  {
    id: "opensc2k",
    name: "OpenSC2K",
    path: CDN_BASE + "games/OpenSC2K/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "Classic", "Retro"],
    badge: "Retro Sim",
    desc: "Open-source WebGL recreation of the classic city simulator SimCity 2000.",
    controls: "Mouse: Select zoning tools, lay pipes, construct buildings and power grids"
  },
  {
    id: "pacman-canvas",
    name: "Pacman Canvas",
    path: CDN_BASE + "games/pacman-canvas/index.htm",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Classic", "Retro"],
    badge: "Classic",
    desc: "Faithful HTML5 canvas recreation of the legendary arcade Pac-Man with original sounds.",
    controls: "Arrow Keys / WASD: Steer Pac-Man | Space: Pause / Start"
  },
  {
    id: "sandspiel",
    name: "Sandspiel",
    path: CDN_BASE + "games/sandspiel/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "Sandbox", "Physics"],
    badge: "Physics",
    desc: "Falling sand cellular automata physics game written in Rust & WebAssembly.",
    controls: "Mouse Left Click: Draw selected element | Right Click: Erase | 1-9: Select element"
  },
  {
    id: "space-company",
    name: "Space Company",
    path: CDN_BASE + "games/SpaceCompany/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Incremental", "Sci-Fi", "Strategy"],
    badge: "Sci-Fi",
    desc: "Deep sci-fi incremental simulation \u2014 harvest solar energy, colonize planets, and build Dyson spheres.",
    controls: "Mouse: Manage industry, research technologies, build rockets"
  },
  {
    id: "teterjs",
    name: "Teterjs",
    path: CDN_BASE + "games/teterjs/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Arcade", "Puzzle", "Classic"],
    badge: "Puzzle",
    desc: "Crisp JavaScript block puzzle with ghost piece preview, hold queue, and level progression.",
    controls: "Left / Right: Move | Up: Rotate CW | Z: Rotate CCW | C: Hold | Space: Hard drop"
  },
  {
    id: "flappy-2048",
    name: "Flappy 2048",
    path: CDN_BASE + "games/flappy-2048/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Puzzle", "Casual"],
    badge: "Casual",
    desc: "Wild hybrid of Flappy Bird and 2048 \u2014 flap your number tile through walls with matching values.",
    controls: "Spacebar / Click: Flap tile upward"
  },
  {
    id: "connect-four",
    name: "Connect Four",
    path: CDN_BASE + "games/connect-four/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Board", "Classic"],
    badge: "Board",
    desc: "Classic 4-in-a-row token drop game with smart minimax AI and pass-and-play multiplayer.",
    controls: "Mouse: Click column slot to drop token"
  },
  {
    id: "tictactoe",
    name: "Tic-Tac-Toe AI",
    path: CDN_BASE + "games/tictactoe/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Classic", "Casual"],
    badge: "Casual",
    desc: "Unbeatable Minimax AI Tic-Tac-Toe featuring customizable board themes and difficulty tiers.",
    controls: "Mouse: Click empty square to place X or O"
  },
  {
    id: "tower-game",
    name: "Tower Stacker",
    path: CDN_BASE + "games/tower-game/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Physics", "Casual"],
    badge: "Casual",
    desc: "Addictive high-rise tower stacking arcade \u2014 tap with precision timing to stack floors to the clouds.",
    controls: "Click / Spacebar: Drop current tower block"
  },
  {
    id: "wordle",
    name: "Wordle Unlimited",
    path: CDN_BASE + "games/wordle/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Word", "Logic"],
    badge: "Word",
    desc: "Clean HTML5 recreation of the 5-letter daily word guessing puzzle with infinite replayability.",
    controls: "Keyboard: Type letters | Enter: Submit guess | Backspace: Erase letter"
  },
  {
    id: "progress-knight",
    name: "Progress Knight",
    path: CDN_BASE + "games/progress-knight/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Incremental", "RPG", "Strategy"],
    badge: "Incremental",
    desc: "Deep life-simulation incremental RPG \u2014 train swordplay, study arcane magic, and achieve immortality.",
    controls: "Mouse: Assign job tasks, study skills, manage daily schedule"
  },
  {
    id: "alien-invasion",
    name: "Alien Invasion",
    path: CDN_BASE + "games/alien-invasion/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Shooter"],
    badge: "Retro",
    desc: "Classic top-down space arcade shooter built with HTML5 canvas sprite engine.",
    controls: "Arrow Keys / WASD: Move ship | Spacebar: Shoot lasers"
  },
  {
    id: "monster-candy",
    name: "Monster Wants Candy",
    path: CDN_BASE + "games/monster-candy/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Casual", "Match"],
    badge: "Casual",
    desc: "Juicy Phaser-powered candy catching arcade \u2014 tap sweet treats and dodge evil skull bombs.",
    controls: "Mouse Click / Touch: Catch candies before they hit the ground"
  },
  {
    id: "sorades",
    name: "Starship Sorades 13K",
    path: CDN_BASE + "games/sorades/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Bullet Hell", "Space"],
    badge: "JS13K",
    desc: "Hyper-intense 13KB vertical bullet-hell shmup with screen-filling boss laser patterns.",
    controls: "Arrow Keys / WASD: Steer fighter | Spacebar: Primary fire | Shift: Focus movement"
  },
  {
    id: "space-invaders",
    name: "Space Invaders HTML5",
    path: CDN_BASE + "games/space-invaders/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Shooter"],
    badge: "Classic",
    desc: "Crisp HTML5 recreation of the 1978 arcade alien defense game with classic destructible bunkers.",
    controls: "Left / Right Arrows: Move cannon | Spacebar: Fire laser"
  },
  {
    id: "survivor",
    name: "Survivor Arena",
    path: CDN_BASE + "games/survivor/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Arena", "Survival"],
    badge: "Action",
    desc: "Intense top-down dual-stick zombie arena survivor with shotgun spreads and powerups.",
    controls: "WASD: Move | Mouse: Aim and shoot swarming zombies"
  },
  {
    id: "3d-chess",
    name: "3D Hartwig Chess",
    path: CDN_BASE + "games/3d-chess/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Board", "3D"],
    badge: "3D Board",
    desc: "Elegant 3D CSS/WebGL Bauhaus Hartwig chess board with smooth perspective orbits.",
    controls: "Mouse Click / Drag: Select piece and make legal moves"
  },
  {
    id: "onslaught",
    name: "Onslaught Arena",
    path: CDN_BASE + "games/onslaught/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Arena", "Medieval"],
    badge: "Featured",
    desc: "Lost Decade Games medieval arena hack-and-slash \u2014 blast goblin hordes with magical crossbows.",
    controls: "WASD: Move hero | Mouse: Aim and fire arrows / magic spells"
  },
  {
    id: "mariohtml5",
    name: "Mario HTML5",
    path: CDN_BASE + "games/mariohtml5/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Platformer", "Retro", "Classic"],
    badge: "Retro",
    desc: "Full HTML5 canvas recreation of Super Mario with mushroom powerups, pipes, and Goombas.",
    controls: "Arrow Keys: Walk / Duck | S: Jump | A: Run / Shoot Fireballs"
  },
  {
    id: "green-mahjong",
    name: "Green Mahjong",
    path: CDN_BASE + "games/green-mahjong/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Board", "Solitaire"],
    badge: "Relaxing",
    desc: "Solitaire tile-matching Mahjong with multiple classic pyramid layouts and clean vector art.",
    controls: "Mouse Click: Select unblocked matching tile pairs"
  },
  {
    id: "custom-tetris",
    name: "Custom Tetris",
    path: CDN_BASE + "games/custom-tetris/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Arcade", "Puzzle", "Tetris"],
    badge: "Retro",
    desc: "Ondras highly configurable JavaScript falling block puzzle with custom grid dimensions.",
    controls: "Left / Right: Shift block | Up: Rotate | Down: Drop"
  },
  {
    id: "jolly-jumper",
    name: "Jolly Jumper",
    path: CDN_BASE + "games/jolly-jumper/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Casual", "Endless"],
    badge: "Casual",
    desc: "Bouncy vertical platform jumper \u2014 leap across springs, clouds, and moving platforms.",
    controls: "Left / Right Arrows or A / D: Steer jumper left and right"
  },
  {
    id: "captain-rogers",
    name: "Captain Rogers",
    path: CDN_BASE + "games/captain-rogers/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Action", "Space"],
    badge: "Sci-Fi",
    desc: "Asteroid belt escape pilot game by Enclave Games \u2014 collect star tokens and avoid space mines.",
    controls: "Spacebar / Touch / Mouse Click: Thrust jetpack upward"
  },
  {
    id: "coil",
    name: "Coil",
    path: CDN_BASE + "games/coil/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Action", "Minimal"],
    badge: "Minimal",
    desc: "Hypnotic circular mouse-dodging game \u2014 enclose glowing particles within your energy trail.",
    controls: "Mouse Movement: Steer light trail and encircle energy nodes"
  },
  {
    id: "floppybird",
    name: "Floppy Bird HTML5",
    path: CDN_BASE + "games/floppybird/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Casual", "Flappy"],
    badge: "Casual",
    desc: "Smooth CSS3/HTML5 Flappy Bird clone with authentic sound effects and high score saving.",
    controls: "Spacebar / Mouse Click / Touch: Flap wings"
  },
  {
    id: "pacman",
    name: "Pacman JS",
    path: CDN_BASE + "games/pacman/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Classic", "Retro"],
    badge: "Classic",
    desc: "Lucio Panepinto full-featured canvas Pac-Man with authentic maze pathfinding AI.",
    controls: "Arrow Keys: Steer Pac-Man | Space: Start / Pause"
  },
  {
    id: "drakonas",
    name: "Drakonas",
    path: CDN_BASE + "games/drakonas/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["RPG", "Action", "Fantasy"],
    badge: "RPG",
    desc: "Action fantasy RPG where you battle dragons, cast fireball spells, and explore ruins.",
    controls: "WASD / Arrows: Move | Space: Attack | 1-3: Spells"
  },
  {
    id: "digger",
    name: "Digger Remastered",
    path: CDN_BASE + "games/digger/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Classic"],
    badge: "Retro",
    desc: "Windmill Software 1983 classic Digger remastered in modern HTML5 canvas.",
    controls: "Arrow Keys: Dig tunnels & steer digger | F1: Fire weapon"
  },
  {
    id: "ceros-snake",
    name: "Ceros Snake",
    path: CDN_BASE + "games/ceros-snake/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Snake", "Retro"],
    badge: "Arcade",
    desc: "Vibrant arcade snake with speed boosts, collectible gems, and obstacle grids.",
    controls: "Arrow Keys / WASD: Steer snake"
  },
  {
    id: "openpanzer",
    name: "OpenPanzer",
    path: CDN_BASE + "games/openpanzer/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Wargame", "Hex"],
    badge: "Wargame",
    desc: "Deep tactical turn-based WWII hex grid wargame recreating historical battlefield operations.",
    controls: "Mouse: Select armored divisions, give movement & bombardment orders"
  },
  {
    id: "hotfix",
    name: "Hotfix",
    path: CDN_BASE + "games/hotfix/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Cyber", "Puzzle"],
    badge: "Sci-Fi",
    desc: "Fast cyber security puzzle action \u2014 patch memory leaks and eliminate rogue server viruses.",
    controls: "Arrow Keys / WASD: Move avatar | Space: Deploy software patches"
  },
  {
    id: "hurry",
    name: "Hurry!",
    path: CDN_BASE + "games/hurry/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Action", "Speed", "Casual"],
    badge: "Speed",
    desc: "Fast-paced timer countdown survival game by Hugh Kennedy \u2014 grab glowing clock nodes.",
    controls: "WASD / Arrow Keys: Move character | Dodge laser barriers"
  },
  {
    id: "octocat-jump",
    name: "Octocat Jump",
    path: CDN_BASE + "games/octocat-jump/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Platformer", "Endless"],
    badge: "Casual",
    desc: "GitHub Game Off platform jumper starring Octocat \u2014 collect commit coins and climb higher.",
    controls: "Left / Right Arrow Keys: Move Octocat across floating ledges"
  },
  {
    id: "raging-gardens",
    name: "Raging Gardens",
    path: CDN_BASE + "games/raging-gardens/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Action", "Stealth", "Retro"],
    badge: "Stealth",
    desc: "Stealth garden ninja action \u2014 sneak past angry guard dogs, grab carrots, and escape.",
    controls: "Arrow Keys / WASD: Move ninja | Space: Sneak / Dash"
  },
  {
    id: "save-the-forest",
    name: "Save the Forest",
    path: CDN_BASE + "games/save-the-forest/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Tower Defense", "Casual"],
    badge: "Defense",
    desc: "Strategic environmental defense game \u2014 stop wildfire spread and plant saplings.",
    controls: "Mouse: Click to deploy water pumps and clear firebreak paths"
  },
  {
    id: "spashal",
    name: "Spashal",
    path: CDN_BASE + "games/spashal/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Space", "Physics"],
    badge: "Physics",
    desc: "Orbital physics space maneuver game \u2014 guide rocket trajectories around planetary gravity wells.",
    controls: "Left / Right: Rotate ship | Up Arrow / Space: Fire main rocket booster"
  },
  {
    id: "zedinvaders",
    name: "Zed Invaders",
    path: CDN_BASE + "games/zedinvaders/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Shooter"],
    badge: "Retro",
    desc: "High-tempo space invaders tribute featuring pulsing neon graphics and bonus waves.",
    controls: "Left / Right Arrows: Move | Spacebar: Fire rapid plasma beams"
  },
  {
    id: "avabranch",
    name: "Avabranch",
    path: CDN_BASE + "games/avabranch/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Physics", "Casual"],
    badge: "Puzzle",
    desc: "Charming branching physics puzzle \u2014 guide seed sprouts to open sunlight blossoms.",
    controls: "Mouse: Click branch joints to split and redirect energy flow"
  },
  {
    id: "heal-em-all",
    name: "Heal Em All",
    path: CDN_BASE + "games/heal-em-all/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Puzzle", "Casual"],
    badge: "Strategy",
    desc: "Reverse zombie strategy puzzle \u2014 synthesize antidotes and cure zombie hordes back to humans.",
    controls: "Mouse: Deploy cure syringes, set barricades, and guide survivors"
  },
  {
    id: "marble-soccer",
    name: "Marble Soccer 3D",
    path: CDN_BASE + "games/marble-soccer/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Sports", "3D", "Physics"],
    badge: "3D Sports",
    desc: "Physics 3D soccer simulation by Jerome Etienne \u2014 steer rolling marbles to score goals.",
    controls: "WASD / Arrows: Steer soccer marble | Space: Boost dash"
  },
  {
    id: "cellmates",
    name: "Cellmates",
    path: CDN_BASE + "games/cellmates/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Puzzle", "Stealth", "Adventure"],
    badge: "Stealth",
    desc: "Cooperative prison stealth escape puzzle \u2014 switch between inmates and evade security guards.",
    controls: "WASD / Arrows: Move active prisoner | Space: Switch prisoner | E: Interact"
  },
  {
    id: "emulatorjs",
    name: "EmulatorJS",
    path: CDN_BASE + "emulators/Emulatorjs/index.html",
    category: "emulators",
    shelf: "emulators",
    tags: ["Emulator", "Retro", "Multi-System"],
    badge: "Emulator",
    desc: "Multi-console retro emulator supporting NES, SNES, GBA, GBC, N64, Genesis, PS1 with ROM drag-and-drop.",
    controls: "Drag & drop any ROM file or browse local files. Supports gamepad & custom keyboard mapping."
  },
  {
    id: "anura-os",
    name: "Anura OS",
    path: CDN_BASE + "emulators/anuraOS.html",
    category: "emulators",
    shelf: "emulators",
    tags: ["Emulator", "OS", "Sandbox"],
    badge: "Virtual OS",
    desc: "Complete desktop operating system running directly in your browser with Linux/x86 app emulation.",
    controls: "Mouse & Keyboard: Full desktop window manager, terminal, file system, and browser apps"
  },
  {
    id: "iodine-gba",
    name: "IodineGBA (GBA Emulator)",
    path: CDN_BASE + "emulators/iodinegba/index.html",
    category: "emulators",
    shelf: "emulators",
    tags: ["Emulator", "Retro", "GBA"],
    badge: "GBA Emulator",
    desc: "High-accuracy pure JavaScript Game Boy Advance emulator \u2014 load .gba ROMs and play instantly.",
    controls: "Load ROM file from disk | Keyboard: Z (A), X (B), Enter (Start), Shift (Select), Arrows (D-Pad)"
  },
  {
    id: "cyberchef",
    name: "CyberChef",
    path: CDN_BASE + "other/CyberChef/index.html",
    category: "other",
    shelf: "other",
    tags: ["Tools", "Utility", "Cryptography"],
    badge: "Utility",
    desc: "The cyber Swiss Army knife by GCHQ for encoding, decoding, hashing, encryption, regex, and hex editing.",
    controls: "Mouse: Drag operations into recipe pipeline, paste input, inspect output"
  },
  {
    id: "gust-browser",
    name: "GUST",
    path: CDN_BASE + "browsers/GUST.html",
    category: "other",
    shelf: "other",
    tags: ["Browser", "Proxy", "Utility"],
    badge: "Browser",
    desc: "Full-featured web proxy browser client with tab management and stealth browsing.",
    controls: "Type any web address or search query in the address bar"
  },
  {
    id: "incognito-browser",
    name: "Incognito",
    path: CDN_BASE + "browsers/Incognito.html",
    category: "other",
    shelf: "other",
    tags: ["Browser", "Proxy", "Utility"],
    badge: "Browser",
    desc: "Fast, privacy-focused proxy gateway designed for unblocked web exploration.",
    controls: "Enter search terms or URL in the navigation bar"
  },
  {
    id: "interstellar-browser",
    name: "Interstellar",
    path: CDN_BASE + "browsers/Interstellar.html",
    category: "other",
    shelf: "other",
    tags: ["Browser", "Proxy", "Utility"],
    badge: "Browser",
    desc: "Modern, streamlined web proxy interface with fast loading and responsive controls.",
    controls: "Type search query or website destination into the bar"
  },
  {
    id: "scramjet-browser",
    name: "Scramjet",
    path: CDN_BASE + "browsers/Scramjet.html",
    category: "other",
    shelf: "other",
    tags: ["Browser", "Proxy", "Utility"],
    badge: "Browser",
    desc: "High-performance web proxy client built on modern service worker proxy technologies.",
    controls: "Enter URL or search keyword into the navigation search bar"
  }
];
