/* ================================================================
   DRAGON GAMING PLATFORMS — CDN / STANDALONE DATA CATALOG
   ================================================================ */
const CDN_BASE = "https://dragon-gaming-platforms.github.io/Dragon-Gaming-Platforms/";

const GAMES_DATA = [
  {
    id: "eaglercraft-1-12-2-wasm",
    name: "Eaglercraft 1.12.2 WASM",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-1.12.2-offline-WASM.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Sandbox", "Survival", "3D", "WASM"],
    badge: "WASM",
    desc: "Full Minecraft 1.12.2 running offline directly in your browser via WebAssembly.",
    controls: "WASD: Move | Space: Jump | Left Click: Mine / Attack | Right Click: Place / Interact | E: Inventory | Esc: Pause"
  },
  {
    id: "eaglercraft-1-12-2-js",
    name: "Eaglercraft 1.12.2 JS",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-JS-1.12.2.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Sandbox", "Survival", "3D"],
    badge: "3D",
    desc: "JavaScript client for Minecraft 1.12.2 with online multiplayer and singleplayer worlds.",
    controls: "WASD: Move | Space: Jump | Mouse: Look / Mine | E: Inventory | Esc: Pause"
  },
  {
    id: "eaglercraft-1-8-8-js",
    name: "Eaglercraft 1.8.8 JS",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-JS-1.8.8.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Sandbox", "Survival", "3D", "Multiplayer"],
    badge: "Popular",
    desc: "Classic Minecraft 1.8.8 with server browser, custom skins, and fluid combat.",
    controls: "WASD: Move | Space: Jump | Mouse: Look / Mine | E: Inventory | T: Chat"
  },
  {
    id: "eaglercraft-1-8-8-wasm",
    name: "Eaglercraft 1.8.8 WASM",
    path: CDN_BASE + "games/singlefiles/Eaglercraft-1.8.8-offline-WASM.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Sandbox", "Survival", "3D", "WASM"],
    badge: "WASM",
    desc: "Ultra-fast WebAssembly port of Minecraft 1.8.8 for offline sandbox play.",
    controls: "WASD: Move | Space: Jump | Left Click: Mine | Right Click: Place | Esc: Pause"
  },
  {
    id: "balatro",
    name: "Balatro",
    path: CDN_BASE + "games/singlefiles/Balatro.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Roguelike", "Deckbuilder", "Poker", "Strategy"],
    badge: "Roguelike",
    desc: "Poker roguelike deckbuilder. Combine valid poker hands with unique Joker cards to create synergies.",
    controls: "Mouse: Select / Play Cards / Discard"
  },
  {
    id: "hole-io",
    name: "Hole.io",
    path: CDN_BASE + "games/singlefiles/Hole.io.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Multiplayer", "Physics", "3D"],
    badge: "Multiplayer",
    desc: "Control a ravenous black hole consuming everything from street lamps to skyscrapers across a 3D city.",
    controls: "Mouse Drag / WASD / Arrow Keys: Move Black Hole"
  },
  {
    id: "awesome-tanks-2",
    name: "Awesome Tanks 2",
    path: CDN_BASE + "games/singlefiles/awesometanks2.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Shooter", "Tanks", "Action", "Upgrades"],
    badge: "Action",
    desc: "Blaze through destructible arenas, blast enemy war machines, and upgrade cannons, armor, and lasers.",
    controls: "WASD: Drive | Mouse: Aim and Fire"
  },
  {
    id: "recoil",
    name: "Recoil",
    path: CDN_BASE + "games/singlefiles/Recoil.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Physics", "Shooter", "Action", "Puzzle"],
    badge: "Physics",
    desc: "Navigate tight hazard rooms by weapon recoil propulsion alone! Shoot targets to fling your character.",
    controls: "Mouse Aim & Left Click: Shoot / Propel"
  },
  {
    id: "ragdoll-archers",
    name: "Ragdoll Archers",
    path: CDN_BASE + "games/singlefiles/Ragdoll-Archers.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Physics", "Archery", "Ragdoll", "Shooter"],
    badge: "Action",
    desc: "Draw your bow and launch precision arrows against hordes of incoming ragdoll enemies and giant bosses.",
    controls: "Mouse Drag: Aim and Charge Bow | Release: Shoot"
  },
  {
    id: "alien-invasion",
    name: "Alien Invasion",
    path: CDN_BASE + "games/alien-invasion/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Shooter", "Space", "Retro"],
    badge: "Shooter",
    desc: "Classic mobile-friendly HTML5 space shooter. Blast descending waves of alien invaders and dodge missile barrages.",
    controls: "Left / Right: Steer Fighter | Space: Fire Missiles"
  },
  {
    id: "sorades",
    name: "Sorades 13K",
    path: CDN_BASE + "games/sorades/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Shooter", "Shmup", "JS13K"],
    badge: "Action",
    desc: "High-octane JS13K vertical shmup inspired by Raptor: Call of the Shadows. Dodge bullet patterns and destroy bosses.",
    controls: "Arrow Keys / WASD: Move Starship | Space / Z: Fire Cannons"
  },
  {
    id: "survivor",
    name: "Survivor",
    path: CDN_BASE + "games/survivor/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Shooter", "Action", "Space"],
    badge: "Action",
    desc: "Playable HTML5 + CSS + JavaScript space shooter remake of the classic 8-bit Survivor game by Scott Schiller.",
    controls: "WASD / Arrow Keys: Fly | Space: Shoot"
  },
  {
    id: "onslaught",
    name: "Onslaught Arena",
    path: CDN_BASE + "games/onslaught/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "Arena", "Medieval", "Combat"],
    badge: "Action",
    desc: "Fast-paced medieval arena combat by Lost Decade Games. Battle endless hordes of goblins, skeletons, and bosses.",
    controls: "WASD: Move | Mouse: Aim and Attack | 1-4: Switch Weapons"
  },
  {
    id: "drakonas",
    name: "Drakonas 3D",
    path: CDN_BASE + "games/drakonas/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Action", "3D", "Three.js", "Shooter"],
    badge: "3D",
    desc: "3D Three.js orbital space combat shoot 'em up. Engage enemy dreadnoughts and interceptors across open space.",
    controls: "Mouse: Aim & Steer | Space / Left Click: Fire Laser Cannons"
  },
  {
    id: "ancient-beast",
    name: "Ancient Beast",
    path: CDN_BASE + "games/AncientBeast/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Strategy", "Turn-Based", "Multiplayer", "Hex"],
    badge: "Strategy",
    desc: "Open-source 3D/2D turn-based tactical strategy game. Materialize mystical beasts and wage hex combat.",
    controls: "Mouse: Select Unit / Move / Attack / Summon"
  },
  {
    id: "hexgl",
    name: "HexGL",
    path: CDN_BASE + "games/HexGL/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Racing", "3D", "WebGL", "Sci-Fi"],
    badge: "3D",
    desc: "Futuristic high-speed WebGL anti-gravity racing game inspired by Wipeout and F-Zero by Thibaut Despoulain.",
    controls: "Left / Right or A / D: Steer | Up: Airbrake | Space: Boost"
  },
  {
    id: "3d-city",
    name: "3D.City",
    path: CDN_BASE + "games/3d.city/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Simulation", "3D", "City Builder", "WebGL"],
    badge: "3D",
    desc: "Interactive 3D Three.js city builder. Place roads, skyscrapers, power plants, and observe dynamic traffic.",
    controls: "Mouse: Rotate Camera / Place Buildings / Zoom"
  },
  {
    id: "spashal",
    name: "Spashal",
    path: CDN_BASE + "games/spashal/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Space", "Survival", "Shooter"],
    badge: "Space",
    desc: "Danger lurks in every corner of deep space! Dodge asteroid fields and dogfight hostile space cruisers.",
    controls: "WASD: Steer Ship | Mouse: Aim & Fire Primary Weapons"
  },
  {
    id: "zedinvaders",
    name: "Zed Invaders",
    path: CDN_BASE + "games/zedinvaders/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Shooter", "Comic", "Action"],
    badge: "Comic",
    desc: "Stylized sci-fi comic shooter based on the ZED graphic novel universe with explosive power-ups.",
    controls: "Left / Right: Steer Hero | Space: Fire Plasma Beams"
  },
  {
    id: "asdf",
    name: "ASDF",
    path: CDN_BASE + "games/asdf/index.html",
    category: "games",
    shelf: "action-3d",
    tags: ["Arcade", "Rhythm", "Typing", "Speed"],
    badge: "Speed",
    desc: "Ultra-fast keyboard agility rhythm game testing pure typing reflex speed.",
    controls: "A, S, D, F Keys: Match On-screen Rhythm Cues"
  },
  {
    id: "space-cadet-pinball",
    name: "Space Cadet Pinball",
    path: CDN_BASE + "games/space-cadet-pinball/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Pinball", "Retro", "Classic"],
    badge: "Classic",
    desc: "The legendary 3D Pinball for Windows - Space Cadet running natively in WebAssembly & HTML5.",
    controls: "Z / /: Left/Right Flippers | Space: Plunger | Space/Arrows: Nudge"
  },
  {
    id: "mariohtml5",
    name: "Infinite Mario HTML5",
    path: CDN_BASE + "games/mariohtml5/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Platformer", "Retro", "Mario", "Classic"],
    badge: "Classic",
    desc: "Robert Kleffner's complete HTML5 JavaScript port of Notch's Infinite Mario Bros with procedural level generation.",
    controls: "A / D or Left / Right: Run | S / Up: Jump | A: Run / Fireball | Esc: Pause"
  },
  {
    id: "pacman",
    name: "HTML5 Pacman",
    path: CDN_BASE + "games/pacman/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Pacman", "Classic"],
    badge: "Retro",
    desc: "Classic HTML5 Pacman with full sound effects, fruit bonuses, ghost vulnerability timers, and high scores.",
    controls: "Arrow Keys: Navigate Maze | S: Sound Toggle"
  },
  {
    id: "pacman-canvas",
    name: "Pacman Canvas",
    path: CDN_BASE + "games/pacman-canvas/index.htm",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Pacman", "Classic", "Retro"],
    badge: "Classic",
    desc: "Complete HTML5 Canvas recreation of Pacman with AI ghost routines, energizers, and sound effects.",
    controls: "Arrow Keys / WASD: Move Pacman | N: New Game"
  },
  {
    id: "space-invaders",
    name: "Space Invaders",
    path: CDN_BASE + "games/space-invaders/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Space", "Retro", "Classic"],
    badge: "Classic",
    desc: "Faithful JavaScript remake of Taito's iconic 1978 Space Invaders arcade machine with destructible bunkers.",
    controls: "Left / Right: Move Cannon | Space: Fire"
  },
  {
    id: "asteroids",
    name: "Asteroids",
    path: CDN_BASE + "games/asteroids/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Space", "Vector", "Retro"],
    badge: "Vector",
    desc: "Pure JavaScript vector arcade space shooter. Blast asteroids into fragments and eliminate flying saucers.",
    controls: "Left / Right: Rotate | Up: Thrust | Space: Fire Lasers"
  },
  {
    id: "duck-hunt",
    name: "Duck Hunt JS",
    path: CDN_BASE + "games/duck-hunt/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Shooter", "Retro", "Classic"],
    badge: "Retro",
    desc: "Faithful recreation of the 8-bit duck shooting gallery with animated dog and level customizer.",
    controls: "Mouse: Aim & Shoot"
  },
  {
    id: "digger",
    name: "Digger",
    path: CDN_BASE + "games/digger/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Boulderdash", "Classic"],
    badge: "Retro",
    desc: "HTML5 version of the iconic 1983 Boulderdash / Digger game by Lutz Roeder with authentic PC speaker sound effects.",
    controls: "Arrow Keys: Dig Tunnels / Push Emeralds | F10: Fire Weapon"
  },
  {
    id: "ceros-snake",
    name: "Ceros Snake",
    path: CDN_BASE + "games/ceros-snake/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Snake", "70s"],
    badge: "Retro",
    desc: "Vintage 70s-style monochrome arcade Snake with authentic retro scanline aesthetics and crisp sound.",
    controls: "WASD / Arrow Keys: Slither"
  },
  {
    id: "snake",
    name: "Snake",
    path: CDN_BASE + "games/snake/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Classic", "Casual"],
    badge: "Retro",
    desc: "Classic retro snake game. Slither, gobble apples to grow longer, and avoid crashing into your own tail.",
    controls: "Arrow Keys / WASD: Change Direction | Space: Pause"
  },
  {
    id: "pong",
    name: "Pong",
    path: CDN_BASE + "games/pong/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Atari", "Classic"],
    badge: "Retro",
    desc: "The game that started video game history: classic 1972 table tennis arcade Pong with responsive AI paddle.",
    controls: "Mouse / Up-Down Arrows: Defend Goal"
  },
  {
    id: "t-rex-runner",
    name: "T-Rex Dino Runner",
    path: CDN_BASE + "games/t-rex-runner/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Runner", "Classic", "Casual"],
    badge: "Popular",
    desc: "The iconic Chromium offline dinosaur runner. Leap over desert cacti and duck under soaring pterodactyls.",
    controls: "Space / Up Arrow: Jump | Down Arrow: Duck"
  },
  {
    id: "crappybird",
    name: "CrappyBird",
    path: CDN_BASE + "games/CrappyBird/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Flappy", "Canvas", "Casual"],
    badge: "Casual",
    desc: "Smooth 60FPS pure JavaScript Canvas2D flappy bird clone with accurate collision and high score tracking.",
    controls: "Space / Click: Flap"
  },
  {
    id: "clumsy-bird",
    name: "Clumsy Bird",
    path: CDN_BASE + "games/clumsy-bird/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Flappy", "Retro", "Canvas"],
    badge: "Arcade",
    desc: "Charming open-source melonJS recreation of the iconic bird flapping obstacle course.",
    controls: "Space / Click / Tap: Flap Wings"
  },
  {
    id: "floppybird",
    name: "Floppy Bird",
    path: CDN_BASE + "games/floppybird/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Flappy", "Retro", "Canvas"],
    badge: "Arcade",
    desc: "Pixel-perfect open source canvas Flappy Bird clone with authentic physics and high score saves.",
    controls: "Space / Click: Flap Wings"
  },
  {
    id: "flappy-2048",
    name: "Flappy 2048",
    path: CDN_BASE + "games/flappy-2048/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Flappy", "2048", "Hybrid"],
    badge: "Hybrid",
    desc: "Brilliant mashup of Flappy Bird and 2048! Flap your tile through obstacles matching your number to double it.",
    controls: "Space / Click: Flap and Merge Numbers"
  },
  {
    id: "crystalquest",
    name: "CrystalQuest",
    path: CDN_BASE + "games/CrystalQuest/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Shooter", "Retro", "Action"],
    badge: "Action",
    desc: "HTML5 remake of the beloved Mac arcade shooter. Collect glowing crystals while dodging kinetic mines.",
    controls: "Mouse: Steer Ship | Space / Click: Shoot"
  },
  {
    id: "banania",
    name: "Banania",
    path: CDN_BASE + "games/Banania/banania.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Retro", "Maze", "Classic"],
    badge: "Retro",
    desc: "Classic DOS maze game recreation. Collect all bananas on the grid while evading roaming monsters.",
    controls: "Arrow Keys: Move Monkey"
  },
  {
    id: "simon",
    name: "Simon Says",
    path: CDN_BASE + "games/simon/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Puzzle", "Memory", "Audio", "Retro"],
    badge: "Memory",
    desc: "Classic 1978 Milton Bradley electronic memory game. Repeat increasingly complex sequences of lights and tones.",
    controls: "Mouse Click: Replicate Light Sequence"
  },
  {
    id: "ball-and-wall",
    name: "Ball and Wall",
    path: CDN_BASE + "games/ball-and-wall/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Breakout", "Retro", "Physics"],
    badge: "Breakout",
    desc: "High-framerate Arkanoid / Breakout arcade remake with dynamic brick patterns and power-ups.",
    controls: "Mouse / Left-Right Arrows: Move Paddle | Space: Launch Ball"
  },
  {
    id: "coil",
    name: "Coil",
    path: CDN_BASE + "games/coil/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Canvas", "Action", "Glow"],
    badge: "Glow",
    desc: "Hypnotic canvas game by Hakim El Hattab. Defeat swirling cosmic enemies by enclosing them in your glowing particle trail.",
    controls: "Mouse: Steer Orb Trail in Full Circles"
  },
  {
    id: "hotfix",
    name: "HotFix",
    path: CDN_BASE + "games/hotfix/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Sci-Fi", "Dodger", "Action"],
    badge: "Sci-Fi",
    desc: "Help Hotfix harvest shimmering stargazers across quantum space while evading deadly bug anomalies.",
    controls: "Arrow Keys / Mouse: Navigate Particle Field"
  },
  {
    id: "hurry",
    name: "Hurry!",
    path: CDN_BASE + "games/hurry/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Speed", "Shooter", "Ludum Dare"],
    badge: "Speed",
    desc: "Adrenaline-fueled 10-second arcade shooter created by Hugh Kennedy for Ludum Dare 27.",
    controls: "Mouse: Aim & Accelerate | Click: Fire Rapid Blaster"
  },
  {
    id: "arashi-js",
    name: "Arashi JS",
    path: CDN_BASE + "games/arashi-js/index.html",
    category: "games",
    shelf: "arcade-retro",
    tags: ["Arcade", "Vector", "Shooter", "Tempest"],
    badge: "Vector",
    desc: "Hypnotic HTML5 vector clone of the classic arcade tube shooter Tempest with pulsing geometric webs.",
    controls: "Arrow Keys: Rotate Around Rim | Space: Fire | Z: Superzapper"
  },
  {
    id: "2048",
    name: "2048",
    path: CDN_BASE + "games/2048/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Numbers", "Addictive", "Casual"],
    badge: "Popular",
    desc: "The iconic sliding tile numbers puzzle by Gabriele Cirulli. Merge identical tiles to reach the 2048 tile.",
    controls: "Arrow Keys / Swipe: Slide Tiles"
  },
  {
    id: "hextris",
    name: "Hextris",
    path: CDN_BASE + "games/Hextris/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Hexagon", "Fast-Paced", "Addictive"],
    badge: "Popular",
    desc: "Fast-paced hexagonal puzzle game. Rotate the outer hexagon to match 3 or more blocks of the same color.",
    controls: "Left / Right Arrow Keys or A / D: Rotate Hexagon"
  },
  {
    id: "canvas-tetris",
    name: "Canvas Tetris",
    path: CDN_BASE + "games/canvas-tetris/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Tetris", "Classic", "Canvas"],
    badge: "Puzzle",
    desc: "Lightweight vanilla HTML5 Canvas Tetris implementation with smooth line clears and classic scoring.",
    controls: "Left / Right: Move | Up: Rotate | Down: Fast Drop"
  },
  {
    id: "custom-tetris",
    name: "Custom Tetris",
    path: CDN_BASE + "games/custom-tetris/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Tetris", "Customizable", "Retro"],
    badge: "Puzzle",
    desc: "Fully customizable Tetris engine by Ond\u0159ej \u017d\u00e1ra. Customize piece shapes, gravity speed, and grid dimensions.",
    controls: "Arrow Keys: Move & Rotate | Space: Drop"
  },
  {
    id: "blockrain",
    name: "Blockrain",
    path: CDN_BASE + "games/blockrain/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Tetris", "Retro", "Canvas"],
    badge: "Puzzle",
    desc: "Gorgeous retro pixel-art Tetris engine with responsive controls, custom palettes, and particle effects.",
    controls: "Arrow Keys: Move & Rotate | Down: Soft Drop | Space: Hard Drop"
  },
  {
    id: "teterjs",
    name: "Teterjs",
    path: CDN_BASE + "games/teterjs/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Tetris", "Casual", "Canvas"],
    badge: "Puzzle",
    desc: "Clean and responsive canvas block drop puzzle with customizable board speeds.",
    controls: "Arrow Keys: Move & Rotate | Space: Drop"
  },
  {
    id: "3d-chess",
    name: "3D Hartwig Chess Set",
    path: CDN_BASE + "games/3d-chess/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Board", "Chess", "3D", "CSS3"],
    badge: "3D",
    desc: "Stunning Bauhaus Josef Hartwig 3D chess set crafted entirely in HTML5, CSS 3D transforms, and JavaScript.",
    controls: "Mouse: Orbit Camera & Select Chess Pieces"
  },
  {
    id: "chess",
    name: "Chess vs AI",
    path: CDN_BASE + "games/chess/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Board", "Strategy", "AI", "Classic"],
    badge: "Strategy",
    desc: "Full chess engine running in browser. Test your tactical prowess against adjustable AI difficulty.",
    controls: "Mouse / Click: Drag and Drop Pieces"
  },
  {
    id: "connect-four",
    name: "Connect Four",
    path: CDN_BASE + "games/connect-four/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Board", "Strategy", "AI", "Classic"],
    badge: "Classic",
    desc: "Slick Connect Four game by Caleb Evans with smart AI, local 2-player mode, and smooth drop animations.",
    controls: "Mouse Click: Drop Disc Into Target Column"
  },
  {
    id: "minesweeper",
    name: "Minesweeper",
    path: CDN_BASE + "games/minesweeper/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Logic", "Classic", "Retro"],
    badge: "Logic",
    desc: "Authentic recreation of the classic Windows logic puzzle. Clear the minefield without detonating a single bomb.",
    controls: "Left Click: Reveal Cell | Right Click: Place Flag"
  },
  {
    id: "sudoku",
    name: "Sudoku",
    path: CDN_BASE + "games/sudoku/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Numbers", "Logic", "Brain"],
    badge: "Logic",
    desc: "Clean and elegant 9x9 Sudoku puzzle generator with multiple difficulty levels and hint assist.",
    controls: "Mouse / Touch: Select Cell | Number Keys 1-9: Enter Digit"
  },
  {
    id: "solitaire",
    name: "Solitaire",
    path: CDN_BASE + "games/solitaire/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Cards", "Klondike", "Classic", "Patience"],
    badge: "Cards",
    desc: "Classic Klondike Solitaire card game. Stack suits in ascending order from Ace to King.",
    controls: "Mouse: Drag and Drop Cards / Click Deck to Draw"
  },
  {
    id: "wordle",
    name: "Wordle Infinite",
    path: CDN_BASE + "games/wordle/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Word", "Logic", "Brain"],
    badge: "Word",
    desc: "Infinite word-guessing challenge with color-coded feedback tiles and complete performance statistics.",
    controls: "Keyboard: Type 5-letter Words | Enter: Submit | Backspace: Delete"
  },
  {
    id: "green-mahjong",
    name: "Green Mahjong",
    path: CDN_BASE + "games/green-mahjong/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Board", "Solitaire", "Mahjong"],
    badge: "Mahjong",
    desc: "Relaxing solitaire Mahjong tile-matching game done in clean HTML5/CSS3 with customizable boards.",
    controls: "Mouse / Touch: Select Matching Unblocked Tiles"
  },
  {
    id: "breaklock",
    name: "Breaklock",
    path: CDN_BASE + "games/breaklock/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Pattern", "Logic", "Casual"],
    badge: "Logic",
    desc: "Addictive pattern lock deduction game combining Mastermind with smartphone pattern unlock mechanics.",
    controls: "Mouse Drag / Touch: Connect Dots to Deduce Secret Pattern"
  },
  {
    id: "tictactoe",
    name: "Tic-Tac-Toe",
    path: CDN_BASE + "games/tictactoe/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Board", "Logic", "AI", "Classic"],
    badge: "Classic",
    desc: "Modern neon Tic-Tac-Toe with unbeatable Minimax AI option and two-player local pass-and-play.",
    controls: "Mouse Click: Place X or O"
  },
  {
    id: "sokoban",
    name: "Sokoban",
    path: CDN_BASE + "games/sokoban/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Logic", "Classic", "Grid"],
    badge: "Puzzle",
    desc: "Classic warehouse keeper puzzle. Push crates into designated storage targets in minimal steps.",
    controls: "Arrow Keys / WASD: Move Pusher"
  },
  {
    id: "aquastax",
    name: "Aquastax",
    path: CDN_BASE + "games/aquastax/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Physics", "Water", "Casual"],
    badge: "Puzzle",
    desc: "Fluid water pipe physics puzzle game. Guide bubbling water into target flasks with strategic placement.",
    controls: "Mouse: Rotate and Place Pipe Connectors"
  },
  {
    id: "heal-em-all",
    name: "Heal 'em All",
    path: CDN_BASE + "games/heal-em-all/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Strategy", "Zombies", "Game Off"],
    badge: "Puzzle",
    desc: "What if the zombie plague could be cured? Deploy antidote injectors to heal infected humans across the grid.",
    controls: "Mouse: Select & Deploy Antidote Doses"
  },
  {
    id: "cellmates",
    name: "Cell Mates",
    path: CDN_BASE + "games/cellmates/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Puzzle", "Physics", "Co-op", "Game Jam"],
    badge: "Puzzle",
    desc: "Global Game Jam puzzle game. Coordinate two linked organic cells through perilous micro-cellular mazes.",
    controls: "Arrow Keys: Steer Coupled Cells"
  },
  {
    id: "openpanzer",
    name: "Open Panzer",
    path: CDN_BASE + "games/openpanzer/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Hex", "WWII", "Tactical"],
    badge: "Strategy",
    desc: "Panzer General tactical WWII hex wargame engine in HTML5. Command armor battalions and tactical aviation.",
    controls: "Mouse: Select Unit / Move / Attack / Inspect Terrain"
  },
  {
    id: "bloons-td4",
    name: "Bloons TD4",
    path: CDN_BASE + "games/singlefiles/Bloons-TD4.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Tower Defense", "Strategy", "Classic"],
    badge: "Popular",
    desc: "Pop incoming waves of colorful balloons by tactically placing and upgrading dart monkeys and cannons.",
    controls: "Mouse: Place and Upgrade Towers | Space: Start Wave"
  },
  {
    id: "tower-defense",
    name: "Canvas Tower Defense",
    path: CDN_BASE + "games/tower-defense/index.html",
    category: "games",
    shelf: "puzzle-strategy",
    tags: ["Strategy", "Tower Defense", "Canvas", "Tactical"],
    badge: "Strategy",
    desc: "Strategic path-building tower defense. Place lasers, cannons, and missile turrets to repel enemy creep waves.",
    controls: "Mouse: Select and Place Defensive Turrets"
  },
  {
    id: "drive-mad",
    name: "Drive Mad",
    path: CDN_BASE + "games/singlefiles/Drive-Mad.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Driving", "Physics", "Obstacle", "3D"],
    badge: "Physics",
    desc: "Physics-based 3D stunt driving challenge with inventive tracks and unique vehicle mechanics.",
    controls: "W / Up: Accelerate | S / Down: Reverse | A / D: Balance"
  },
  {
    id: "moto-x3m-2",
    name: "Moto x3m 2",
    path: CDN_BASE + "games/singlefiles/Moto-x3m-2.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Motorcycle", "Stunts", "Physics", "Racing"],
    badge: "Racing",
    desc: "High-flying bike racing game filled with massive jumps, explosive obstacles, and acrobatic flips.",
    controls: "Up: Accelerate | Down: Brake | Left / Right: Tilt"
  },
  {
    id: "snowrider-3d",
    name: "Snowrider 3D",
    path: CDN_BASE + "games/singlefiles/Snowrider.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["3D", "Endless Runner", "Winter", "Sports"],
    badge: "3D",
    desc: "Hurtle downhill on a high-speed bobsled dodging pine trees, rocks, and icy ravines in true 3D.",
    controls: "Left / Right or A / D: Steer | Up / Space: Jump"
  },
  {
    id: "enduro",
    name: "Enduro",
    path: CDN_BASE + "games/enduro/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Racing", "Retro", "Atari", "Speed"],
    badge: "Retro",
    desc: "Tribute to the classic Atari 2600 racing endurance game. Overtake cars through day, night, fog, and ice.",
    controls: "Left / Right: Steer | Up: Accelerate | Down: Brake"
  },
  {
    id: "skifree",
    name: "SkiFree.js",
    path: CDN_BASE + "games/skifree/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Arcade", "Sports", "Retro", "Classic"],
    badge: "Classic",
    desc: "Faithful remake of the classic Windows 3.1 skiing game. Carve down slopes and flee the Abominable Snow Monster.",
    controls: "Arrow Keys / Mouse: Steer, Accelerate, Jump"
  },
  {
    id: "marble-soccer",
    name: "Marble Soccer 3D",
    path: CDN_BASE + "games/marble-soccer/index.html",
    category: "games",
    shelf: "driving-sports",
    tags: ["Sports", "3D", "Three.js", "Physics"],
    badge: "3D",
    desc: "Exciting 3D Three.js physics marble soccer match by Jerome Etienne with realistic goal collisions.",
    controls: "WASD / Arrow Keys: Roll Marble Toward Opponent Goal"
  },
  {
    id: "vex-8",
    name: "Vex 8",
    path: CDN_BASE + "games/singlefiles/Vex-8.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Platformer", "Parkour", "Agility", "Stickman"],
    badge: "Parkour",
    desc: "The definitive stickman parkour challenge featuring razor traps, wall-climbing, zip lines, and precision jumps.",
    controls: "WASD / Arrow Keys: Run, Jump, Slide | R: Restart"
  },
  {
    id: "dreadhead-parkour",
    name: "Dreadhead Parkour",
    path: CDN_BASE + "games/singlefiles/dreadheadparkour.htm",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Runner", "Parkour", "Physics", "Action"],
    badge: "Action",
    desc: "Flip, vault, and slide across perilous rooftops and urban hazards in fast-paced parkour action.",
    controls: "A / D: Run | W: Jump / Flip | S: Slide"
  },
  {
    id: "escape-road",
    name: "Escape Road",
    path: CDN_BASE + "games/singlefiles/Escape-Road.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Driving", "Action", "3D", "Chaser"],
    badge: "Action",
    desc: "High-octane city car chase! Outrun relentless police cruisers, dodge road blocks, and drift through streets.",
    controls: "A / D or Left / Right: Steer | Space: Brake / Drift"
  },
  {
    id: "heroine-dusk",
    name: "Heroine Dusk",
    path: CDN_BASE + "games/heroine-dusk/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["RPG", "Dungeon Crawler", "Turn-Based", "Retro"],
    badge: "RPG",
    desc: "First-person dungeon crawler RPG. Explore dark labyrinths, battle monsters, and collect legendary relics.",
    controls: "Arrow Keys: Navigate | Mouse / Click: Attack / Cast Spells"
  },
  {
    id: "a-dark-room",
    name: "A Dark Room",
    path: CDN_BASE + "games/adarkroom/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["RPG", "Incremental", "Atmospheric", "Text"],
    badge: "Story",
    desc: "Award-winning minimalist text-based RPG. Stoke the fire, build your village, and explore the desolate wastes.",
    controls: "Mouse / Click: Story Interactions"
  },
  {
    id: "jolly-jumper",
    name: "Jolly Jumper",
    path: CDN_BASE + "games/jolly-jumper/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Platformer", "Endless", "Phaser", "Casual"],
    badge: "Casual",
    desc: "Fast-paced endless vertical platform jumping game built with the Phaser HTML5 framework.",
    controls: "Left / Right Arrow Keys: Steer Hero Onto Platforms"
  },
  {
    id: "monster-candy",
    name: "Monster Wants Candy",
    path: CDN_BASE + "games/monster-candy/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Casual", "Phaser", "Fun"],
    badge: "Casual",
    desc: "Delightful Phaser matching game by Enclave Games. Feed tasty falling candies to the adorable monster.",
    controls: "Mouse Click / Touch: Catch Delicious Sweets"
  },
  {
    id: "octocat-jump",
    name: "Octocat Jump",
    path: CDN_BASE + "games/octocat-jump/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Jumper", "Octocat", "Casual"],
    badge: "Casual",
    desc: "GitHub Game Off entry! Guide GitHub's mascot Octocat jumping higher and higher on bouncy cloud platforms.",
    controls: "Left / Right Arrow Keys: Steer Octocat"
  },
  {
    id: "captain-rogers",
    name: "Captain Rogers",
    path: CDN_BASE + "games/captain-rogers/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Action", "Runner", "Sci-Fi", "ImpactJS"],
    badge: "Sci-Fi",
    desc: "Captain Rogers: Asteroid Belt of Sirius. Dodge cosmic space mines and pilot through deadly asteroid belts.",
    controls: "Mouse Click / Tap: Thrust Rocket Upward"
  },
  {
    id: "raging-gardens",
    name: "Raging Gardens",
    path: CDN_BASE + "games/raging-gardens/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Ninja", "Maze", "Retro"],
    badge: "Action",
    desc: "Control a hungry ninja rabbit sneaking through garden mazes to feast on carrots while evading guard dogs.",
    controls: "Arrow Keys: Move Ninja Rabbit"
  },
  {
    id: "avabranch",
    name: "Avabranch",
    path: CDN_BASE + "games/avabranch/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Procedural", "Fast-Paced", "Dodge"],
    badge: "Speed",
    desc: "Award-winning GitHub Game Off entry by Zolmeister. Dodge branching geometric tree obstacles at breakneck velocity.",
    controls: "Left / Right: Weave Through Branch Fractures"
  },
  {
    id: "save-the-forest",
    name: "Save The Forest",
    path: CDN_BASE + "games/save-the-forest/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Arcade", "Strategy", "JS13K", "Casual"],
    badge: "Action",
    desc: "Intense JS13K wildfire extinguishing game. Deploy water bombers and fire lines to halt devastating forest fires.",
    controls: "Mouse / Click: Extinguish Flames & Plant Firebreaks"
  },
  {
    id: "1255-burgomaster",
    name: "1255 Burgomaster",
    path: CDN_BASE + "games/1255-burgomaster/index.html",
    category: "games",
    shelf: "platformer-adventure",
    tags: ["Strategy", "Medieval", "Management", "Text"],
    badge: "Strategy",
    desc: "Historical medieval city governance simulation. Manage grain stores, taxation, and town defenses.",
    controls: "Mouse / Click: Town Management Decisions"
  },
  {
    id: "sandspiel",
    name: "Sandspiel",
    path: CDN_BASE + "games/sandspiel/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Sandbox", "Physics", "Simulation", "WASM"],
    badge: "WASM",
    desc: "Cellular automata falling sand physics simulator. Experiment with sand, water, fire, plant, oil, and lava.",
    controls: "Mouse: Draw Elements | UI: Select Material / Brush Size"
  },
  {
    id: "opensc2k",
    name: "OpenSC2K",
    path: CDN_BASE + "games/OpenSC2K/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "City Builder", "Isometric", "Retro"],
    badge: "Sim",
    desc: "Open-source HTML5 remake of the iconic isometric SimCity 2000 city simulation.",
    controls: "Mouse: Select Tool / Construct / Pan Map"
  },
  {
    id: "micropolisjs",
    name: "MicropolisJS (SimCity)",
    path: CDN_BASE + "games/micropolisjs/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "City Builder", "Strategy", "Retro"],
    badge: "Sim",
    desc: "Pure JavaScript port of the original open-source SimCity city-building simulation engine.",
    controls: "Mouse: Select Tool / Zone Residential, Commercial & Industrial"
  },
  {
    id: "space-company",
    name: "Space Company",
    path: CDN_BASE + "games/SpaceCompany/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "Sci-Fi", "Incremental", "Space"],
    badge: "Sci-Fi",
    desc: "Deep space exploration incremental game. Harvest resources, research orbital tech, and colonize the galaxy.",
    controls: "Mouse / Click: Research and Base Management"
  },
  {
    id: "progress-knight",
    name: "Progress Knight",
    path: CDN_BASE + "games/progress-knight/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Simulation", "Incremental", "RPG", "Life Sim"],
    badge: "RPG",
    desc: "Life-sim incremental RPG. Work as a beggar or scholar, master holy magic, and unlock immortality through rebirth.",
    controls: "Mouse / Click: Choose Careers, Skills, and Reincarnations"
  },
  {
    id: "tower-game",
    name: "Tower Building Game",
    path: CDN_BASE + "games/tower-game/index.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Arcade", "Physics", "Stacking", "Casual"],
    badge: "Stacking",
    desc: "Addictive skyscraper stacking game. Time the swinging crane release to stack tower floors into the clouds.",
    controls: "Space / Click: Drop Floor Block"
  },
  {
    id: "borg-games",
    name: "Borg Games",
    path: CDN_BASE + "games/singlefiles/Borg-Games.html",
    category: "games",
    shelf: "sandbox-simulation",
    tags: ["Hub", "Arcade", "Retro", "Collection"],
    badge: "Hub",
    desc: "Comprehensive standalone arcade collection featuring classic mini-games and retro simulations.",
    controls: "Interactive Menu UI / On-screen Controls"
  },
  {
    id: "emulatorjs",
    name: "EmulatorJS",
    path: CDN_BASE + "emulators/Emulatorjs/index.html",
    category: "emulators",
    shelf: "emulators",
    tags: ["Emulator", "Retro", "NES", "SNES", "GBA", "N64", "Genesis", "PSX"],
    badge: "Multi-System",
    desc: "Multi-system web emulator supporting NES, SNES, Game Boy, GBA, Genesis, Nintendo 64, and PlayStation with built-in ROM drop zone.",
    controls: "Gamepad / Keyboard Configurable | In-game Settings Menu"
  },
  {
    id: "anura-os",
    name: "Anura OS",
    path: CDN_BASE + "emulators/anuraOS.html",
    category: "emulators",
    shelf: "emulators",
    tags: ["OS", "Linux", "Desktop", "Sandbox"],
    badge: "Web OS",
    desc: "Full-featured web-based operating system with window manager, terminal, apps, and browser environment.",
    controls: "Standard Desktop UI: Windows, Mouse, Keyboard"
  },
  {
    id: "iodinegba",
    name: "IodineGBA",
    path: CDN_BASE + "emulators/iodinegba/index.html",
    category: "emulators",
    shelf: "emulators",
    tags: ["Emulator", "GBA", "Game Boy Advance", "Retro"],
    badge: "GBA",
    desc: "High-performance pure JavaScript Game Boy Advance emulator engine by Grant Galitz with full audio and save support.",
    controls: "Z: A | X: B | A: L | S: R | Enter: Start | Space: Select | Arrow Keys: D-Pad"
  },
  {
    id: "cyberchef",
    name: "CyberChef",
    path: CDN_BASE + "other/CyberChef/index.html",
    category: "tools",
    shelf: "tools",
    tags: ["Tool", "Cryptography", "Encoding", "Utilities"],
    badge: "Utility",
    desc: "The Cyber Swiss Army Knife. Swiss-army tool for encryption, encoding, compression, and data analysis.",
    controls: "Interactive Pipeline Builder UI"
  },
  {
    id: "gust-browser",
    name: "GUST",
    path: CDN_BASE + "browsers/GUST.html",
    category: "tools",
    shelf: "tools",
    tags: ["Browser", "Proxy", "Web", "Privacy"],
    badge: "Proxy",
    desc: "Fast, lightweight web proxy browser with tabbed browsing and cloaking capabilities.",
    controls: "URL Bar / Standard Browser Navigation"
  },
  {
    id: "incognito-browser",
    name: "Incognito",
    path: CDN_BASE + "browsers/Incognito.html",
    category: "tools",
    shelf: "tools",
    tags: ["Browser", "Proxy", "Stealth", "Privacy"],
    badge: "Proxy",
    desc: "Privacy-first web proxy browser designed for seamless browsing and privacy isolation.",
    controls: "URL Bar / Standard Browser Navigation"
  },
  {
    id: "interstellar-browser",
    name: "Interstellar",
    path: CDN_BASE + "browsers/Interstellar.html",
    category: "tools",
    shelf: "tools",
    tags: ["Browser", "Proxy", "Fast", "Stealth"],
    badge: "Proxy",
    desc: "Modern proxy frontend with ultra-fast request routing, customizable themes, and built-in tab cloaking.",
    controls: "URL Bar / Standard Browser Navigation"
  },
  {
    id: "scramjet-browser",
    name: "Scramjet",
    path: CDN_BASE + "browsers/Scramjet.html",
    category: "tools",
    shelf: "tools",
    tags: ["Browser", "Proxy", "NextGen", "Fast"],
    badge: "Proxy",
    desc: "Next-generation web proxy engine offering high compatibility for complex modern web applications.",
    controls: "URL Bar / Standard Browser Navigation"
  }
];

if (typeof window !== "undefined") window.GAMES_DATA = GAMES_DATA;